### PR TITLE
Add more descriptive names to unmapped datatypes in data dictionary

### LINKED ISSUE #708: unmapped datatypes show as Unknown in data dictionary
The data dictionary page shows "Unknown" for data types that are not is its list of datatype.  This should instead show some sort of description of the type derived from the type class.

### PR DESCRIPTION
**Pull request by foster33**
This PR closes [DW-Issue-708](https://github.com/NationalSecurityAgency/datawave/issues/708)

Depends on [dw-type-utils PR 33](https://github.com/NationalSecurityAgency/datawave-type-utils/pull/33)

The data dictionary page previously showed "Unknown" for data types that were not in its list of datatypes. 

This PR adds:
- Use of a class defined data dictionary description for 'Types'
- Adds some new test cases

### CODE REVIEW

**Comment by foster33** [comment]
An example of this change can be seen below:

Before the change:
dw-708-PR-screenshot-before
Both types shown above are 'Unknown'

After the change:
dw-708-PR-screenshot
The types now show as 'Date'.

**Review by jwomeara — COMMENTED** [review]
Interesting...  why would we go with this approach vs. adding intentional descriptions for all of the available types in the data dictionary configuration?  I'm referring to the map of types to descriptions found in DataDictionaryProperties.

**Comment by foster33** [comment]
> Interesting... why would we go with this approach vs. adding intentional descriptions for all of the available types in the data dictionary configuration? I'm referring to the map of types to descriptions found in DataDictionaryProperties.

@jwomeara I personally do not think that this change is intended to be used in replacement of explicitly adding type descriptions in the dictionary configuration. I see it more as removing the 'Unknown' verbiage and replacing it with clearer information in the event that the type is not added to the map for whatever reason (what it was doing originally). So, I agree that the missing types should be added to the config, but I see this as different.

**Comment by ivakegg** [comment]
> Interesting... why would we go with this approach vs. adding intentional descriptions for all of the available types in the data dictionary configuration? I'm referring to the map of types to descriptions found in DataDictionaryProperties.

Yea, I am unsure why we went that way as well.  I think Brian may have been the originator.  I guess this was an attempt to make it prettier somehow.  I would rather have a method on the type itself that returns a pretty name and not have this hardcoded map here.  This PR does answer the call of the ticket.  The question is whether it is worth going farther or removing this map altogether.

**Comment by jwomeara** [comment]
Building the description into the type class itself makes the most sense to me, and should be a relatively simple update.  I guess I'm ok with this as a fallback - I just don't want to confuse users as this is going to expose them to some datawave internals that they might not have seen before.  For example, picking from some of our available types, I think seeing things like the following could potentially be confusing for users: TrimLeadingZeros, RawDate, NoOp, Lc, LcNoDiacritics, HitTerm to name a few...

**Comment by foster33** [comment]
See [dw-type-utils PR 33](https://github.com/NationalSecurityAgency/datawave-type-utils/pull/33) 's comments for more information on the type descriptions being used.

**Pull request closed without merging**
